apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy-mock
  namespace: argo
spec:
  selector:
    app: oauth2-proxy-mock
  ports:
  - port: 4180
    targetPort: 4180
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy-mock
  namespace: argo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy-mock
  template:
    metadata:
      labels:
        app: oauth2-proxy-mock
    spec:
      containers:
      - name: oauth2-proxy-mock
        image: python:3.11-slim
        ports:
        - containerPort: 4180
        command: ["sh","-c"]
        args:
        - |-
          set -e
          mkdir -p /app
          cat > /app/server.py <<'PY'
          from http.server import BaseHTTPRequestHandler, HTTPServer
          import urllib.parse as u
          import html
          class H(BaseHTTPRequestHandler):
            def do_GET(self):
              parsed = u.urlparse(self.path)
              path = parsed.path
              qs = u.parse_qs(parsed.query)
              if path.startswith('/oauth2/redirect') or path.startswith('/oauth2/callback') or 'redirect' in qs:
                redirect = qs.get('redirect',['/'])[0]
                # set a simple cookie and redirect back
                self.send_response(302)
                self.send_header('Set-Cookie','_oauth2_mock=1; Path=/; HttpOnly')
                self.send_header('Location', html.escape(redirect))
                self.end_headers()
              else:
                self.send_response(200)
                self.send_header('Content-Type','text/plain')
                self.end_headers()
                self.wfile.write(b'ok')

          if __name__ == '__main__':
            HTTPServer(('0.0.0.0',4180), H).serve_forever()
          PY
          python /app/server.py
